### ISSUE TITLE
failing to find peers/routes

### ISSUE THREAD

**Issue by dismantl** [opentechinstitute/olsrd#8]
In the Linux client, olsrd is starting fine, and outputting no errors, but sometimes fails to find peers or routes. More information to follow tomorrow.

**Comment by jheretic** [comment]
I think @technosopher determined that this was due to the wireless interface misbehaving after a state change. @technosopher, can you confirm?

**Comment by technosopher** [comment]
I'm 85% confident that wireless driver quirkiness has something to do
with this problem, but I think the underlying problem is also somewhat
larger than that.  We've seen this behavior on Debian and Ubuntu, even
when using wireless chipsets/drivers that should cleanly support
IBSS_RSN.  In short, then: this is a big problem with a lot of
unknowns, and may require quite a bit of digging to fully unravel.

**Comment by dismantl** [comment]
@technosopher, is this still an outstanding issue?

**Comment by technosopher** [comment]
Yes indeed.  Although I still am not at all sure what's going on behind the scenes, I suspect that the problem lies either (a) with the rampant, silent channel hoping and merging that seems to happen when a Linux client is in the presence of multiple networks with the same BSSIDs and ESSIDs, or (b) some bizzare interaction between olsrd and IBSS_RSN.  The first option is the more likely, I think, which means that we should probably implement the feature that will dynamically generate BSSIDs from the hash of a network's SSID and channel before digging into this issue much further.

**Comment by jheretic** [comment]
I'm pretty sure this is no longer relevant, @technosopher can you confirm?
